name: CI

on:
  push:
    branches: [ master, release/1.x ]
  pull_request:
    branches: [ master, release/1.x ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.1', '8.2', '8.3' ]

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, zip
          coverage: none

      - name: Install 7zip
        run: sudo apt-get install -y p7zip-full

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: vendor/bin/phpunit --no-progress

